Задача 1

О непрерывной равномерно распределённой случайной величине B известно, что её дисперсия равна 0.2. Можно ли найти правую границу величины B и её среднее значение зная, что левая граница равна 0.5? Если да, найдите их.

D(X)=(b−a)**2/12
a - левая граница
b - правая граница
SQRT(12*D(X))+a =b
M(X)=(a+b)/2

In [4]:
import math
a=0.5
D=0.2
b = math.sqrt((12*D))+a
M=(a+b)/2
print('Правая граница В =', b)
print('Математическое ожидание B =', M)

Правая граница В = 2.049193338482967
Математическое ожидание B = 1.2745966692414834


Задача 2

На сколько сигм (средних квадратических отклонений) отклоняется рост человека, равный 190 см, от математического ожидания роста в популяции,в которой M(X) = 178 и D(X) = 25?
 

sigma**2=D(X)

In [6]:
D2=25
M2=178
growth = 190
sigma=math.sqrt(D2)
delta = (190 -178)/sigma
print('Рост человека отклоняется на ',delta,'сигм' )

Рост человека отклоняется на  2.4 сигм


Задача 3

Рост взрослого населения города X имеет нормальное распределение, причём, средний рост равен 174 см, а среднее квадратическое отклонение равно 8 см. С помощью правил стандартного отклонения, двух и трёх сигм посчитайте, какова вероятность того, что случайным образом выбранный взрослый человек имеет рост:

больше 182 см?
больше 190 см?
от 166 см до 190 см?
от 166 см до 182 см?
от 158 см до 190 см?
не выше 150 см или не ниже 190 см?
не выше 150 см или не ниже 198 см?
ниже 166 см?

Правило трёх сигм  — практически все значения нормально распределённой случайной величины лежат в интервале (Xср - 3сигма; Xср +3сигма). Более строго — приблизительно с вероятностью 0,9973 значение нормально распределённой случайной величины лежит в указанном интервале. 
На отрезке от  −σ  до  +σ  расположено около 68 % наблюдений,
от  −2σ  до  +2σ  — 95.4 %,
и от  −3σ  до  +3σ  — 99.72 %.

In [9]:
sigma3=8
mean3 = 174
d1 = mean3 - sigma3
d2 = mean3 + sigma3
d3 = mean3 - 2*sigma3
d4 = mean3 + 2*sigma3
d5 = mean3 - 3*sigma3
d6 = mean3 + 3*sigma3
print(d1,d2)
print(d3,d4)
print(d5,d6)

166 182
158 190
150 198


In [29]:
v1 = 0.68
v2 = 0.954
v3 = 0.9972
v4 = (1-0.9972)

больше 182 см?

In [23]:
v_1=((v2-v1)/2)+((v3-v2)/2)+(v4/2)
v_1

0.15999999999999998

больше 190 см?

In [24]:
v_2=((v3-v2)/2)+(v4/2)
v_2

0.02300000000000002

от 166 см до 190 см? 

In [25]:
v_3 = v1+((v2-v1)/2)
v_3

0.817

от 166 см до 182 см?     

In [20]:
v1

0.68

от 158 см до 190 см?

In [21]:
v2

0.954

не выше 150 см или не ниже 190 см?


In [26]:
v_4=v4/2+((v3-v2)/2)+(v4/2)
v_4

0.024400000000000033

не выше 150 см или не ниже 198 см?

In [27]:
v4

0.0028000000000000247

ниже 166 см?

In [28]:
v_5=v4/2+((v3-v2)/2)+((v2-v1)/2)
v_5

0.15999999999999998

Задача 4 (на подумать)

Каким образом связаны между собой понятие квантиля и правила двух и трёх сигм?

Данное задание - на подумать, оформлять его не обязательно. Этот вопрос мы обсудим в начале следующего занятия.